document.addEventListener('DOMContentLoaded',()=>{
 const cards=[...document.querySelectorAll('.gallery-card')],filters=[...document.querySelectorAll('.gallery-filters button')],box=document.querySelector('.lightbox');if(!cards.length||!box)return;
 const image=box.querySelector('img'),title=box.querySelector('strong'),place=box.querySelector('figcaption span'),counter=box.querySelector('small');let visible=[...cards],index=0,lastFocus;
 const show=n=>{if(!visible.length)return;index=(n+visible.length)%visible.length;const card=visible[index],source=card.querySelector('img');image.src=source.currentSrc||source.src;image.alt=source.alt;title.textContent=card.querySelector('h3').textContent;place.textContent=card.querySelector('span').textContent;counter.textContent=`${index+1} / ${visible.length}`};
 const open=card=>{visible=cards.filter(item=>!item.classList.contains('is-hidden'));lastFocus=document.activeElement;show(Math.max(0,visible.indexOf(card)));box.classList.add('is-open');box.setAttribute('aria-hidden','false');document.body.style.overflow='hidden';box.querySelector('.lightbox-close').focus()};
 const close=()=>{box.classList.remove('is-open');box.setAttribute('aria-hidden','true');document.body.style.overflow='';if(lastFocus)lastFocus.focus()};
 const filter=value=>{filters.forEach(button=>{const active=button.dataset.filter===value;button.classList.toggle('active',active);button.setAttribute('aria-pressed',String(active))});cards.forEach(card=>card.classList.toggle('is-hidden',value!=='all'&&!card.dataset.category.split(' ').includes(value)));document.querySelector('#gallery').scrollIntoView({behavior:'smooth',block:'start'})};
 filters.forEach(button=>button.addEventListener('click',()=>filter(button.dataset.filter)));cards.forEach(card=>{card.tabIndex=0;card.addEventListener('click',()=>open(card));card.addEventListener('keydown',event=>{if(event.key==='Enter'||event.key===' '){event.preventDefault();open(card)}})});
 document.querySelectorAll('[data-filter-target]').forEach(button=>button.addEventListener('click',()=>filter(button.dataset.filterTarget)));document.querySelectorAll('[data-gallery-index]').forEach(button=>button.addEventListener('click',()=>open(cards[Number(button.dataset.galleryIndex)])));
 box.querySelector('.lightbox-close').addEventListener('click',close);box.querySelector('.lightbox-prev').addEventListener('click',()=>show(index-1));box.querySelector('.lightbox-next').addEventListener('click',()=>show(index+1));box.addEventListener('click',event=>{if(event.target===box)close()});document.addEventListener('keydown',event=>{if(!box.classList.contains('is-open'))return;if(event.key==='Escape')close();if(event.key==='ArrowLeft')show(index-1);if(event.key==='ArrowRight')show(index+1)});
});
