(function () {
  'use strict';
  const $ = (s, c = document) => c.querySelector(s);
  const key = document.body.dataset.location;
  const config = {
    gurgaon: { name: 'Gurgaon', hero: 'image/home-hero-luxury-evening-v2.png', intro: 'Gurgaon combines established corporate districts, premium residential corridors and developing sectors. Property decisions here benefit from careful comparison of commute, neighbourhood services and the exact micro-market.', localities: ['Golf Course Road', 'Dwarka Expressway', 'Sohna Road', 'MG Road'], types: ['Premium apartments', 'Family villas', 'Managed rentals', 'Office spaces'], note: 'Travel time can vary sharply by corridor. Review peak-hour access, neighbourhood maturity, maintenance and legal records.' },
    noida: { name: 'Noida', hero: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=1800&q=84', intro: 'Noida offers residential sectors, expressway communities and established employment districts.', localities: ['Sector 150', 'Sector 137', 'Sector 75', 'Sector 78'], types: ['Residential apartments', 'Metro-linked rentals', 'New communities', 'Business spaces'], note: 'Compare sector access, existing occupancy, project status and everyday infrastructure.' },
    greater: { name: 'Greater Noida', hero: 'https://images.unsplash.com/photo-1449157291145-7efd050a4d0e?auto=format&fit=crop&w=1800&q=84', intro: 'Greater Noida includes planned sectors, growing residential catchments and plotted development corridors.', localities: ['Greater Noida West', 'Techzone', 'Yamuna Expressway', 'Jaypee Greens'], types: ['Family apartments', 'Residential plots', 'New projects', 'Selected rentals'], note: 'Verify site access, title, land use, authority approvals and construction status.' },
    delhi: { name: 'Delhi', hero: 'https://images.unsplash.com/photo-1587474260584-136574528ed5?auto=format&fit=crop&w=1800&q=84', intro: 'Delhi is a mature, highly varied property market spanning planned sub-cities, established colonies and commercial districts.', localities: ['Dwarka', 'Rohini', 'South Delhi', 'West Delhi'], types: ['Established homes', 'Builder floors', 'City rentals', 'Commercial addresses'], note: 'Check title history, sanctioned plans, building condition, parking and applicable local rules.' }
  }[key];
  if (!config) return;
  document.documentElement.style.setProperty('--location-hero', `url('${config.hero}')`);
  const localPreview = location.protocol === 'file:' || (['localhost', '127.0.0.1'].includes(location.hostname) && location.port && location.port !== '5000');
  const origin = String(window.LANDLINE_API_ORIGIN || (localPreview ? 'http://localhost:5000' : location.origin)).replace(/\/$/, '');
  const esc = (value) => String(value ?? '').replace(/[&<>"']/g, (char) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[char]);
  const money = (property) => property.price_label || (Number(property.price) >= 1e7 ? `₹${(Number(property.price) / 1e7).toFixed(2)} Cr` : `₹${(Number(property.price) / 1e5).toFixed(2)} Lakh`);
  const card = (property) => `<article class="property-card"><div class="property-media"><img src="${property.cover_image ? `${origin}${property.cover_image}` : 'image/home-hero-luxury-evening-v2.png'}" alt="${esc(`${property.title} in ${property.city}`)}" loading="lazy"></div><div class="property-body"><h3>${esc(property.title)}</h3><p class="location">${esc([property.locality, property.city].filter(Boolean).join(', '))}</p><p class="price">${esc(money(property))}</p><div class="card-actions"><a class="btn" href="property-details.html?slug=${encodeURIComponent(property.slug)}">View Details</a><a class="btn btn-dark" href="contact.html?property=${property.id}">Enquire</a></div></div></article>`;

  document.addEventListener('DOMContentLoaded', async () => {
    const mount = $('#location-content');
    mount.innerHTML = `<section class="section"><div class="container location-overview"><article><span class="eyebrow">Local market context</span><h2>Understanding Property in ${config.name}</h2><p>${config.intro}</p><div class="location-actions"><a class="btn btn-dark" href="featured-properties.html?location=${encodeURIComponent(config.name)}">Buy in ${config.name}</a><a class="btn" href="rent.html?location=${encodeURIComponent(config.name)}">Rent in ${config.name}</a><a class="btn" href="new-projects.html?location=${encodeURIComponent(config.name === 'Delhi' ? 'Delhi NCR' : config.name)}">New Projects</a></div></article><aside class="location-facts"><h3>Property types to explore</h3>${config.types.map((item) => `<p>✓ ${item}</p>`).join('')}</aside></div></section><section class="section alt"><div class="container"><div class="section-head"><div><span class="eyebrow">Current inventory</span><h2>Property Options in ${config.name}</h2></div></div><div class="property-grid" id="location-properties"><div class="empty">Loading current properties…</div></div></div></section><section class="section" id="localities"><div class="container"><div class="section-head"><div><span class="eyebrow">Neighbourhoods</span><h2>Popular Localities in ${config.name}</h2></div></div><div class="info-grid">${config.localities.map((item) => `<article class="info-card"><h3>${item}</h3><p>Explore availability and property types in this locality.</p><a href="featured-properties.html?location=${encodeURIComponent(item)}" class="btn">Explore</a></article>`).join('')}</div></div></section><section class="section alt"><div class="container location-overview"><article><span class="eyebrow">Useful local guidance</span><h2>What to Consider in ${config.name}</h2><p>${config.note}</p></article><aside class="location-facts"><h3>Before you shortlist</h3><p>Visit at different times.</p><p>Check property documents.</p><p>Confirm current pricing and availability.</p><p>Review recurring ownership or rental costs.</p></aside></div></section><section class="section dark"><div class="container"><div class="cta"><div><h2>Need Help Finding Property in ${config.name}?</h2><p>Share your preferred locality, budget and property type.</p></div><a class="btn btn-gold" href="contact.html?location=${encodeURIComponent(config.name)}">Get Expert Assistance</a></div></div></section>`;
    try {
      const response = await fetch(`${origin}/api/properties?location=${encodeURIComponent(config.name)}&limit=3`);
      const result = await response.json().catch(() => null); if (!response.ok) throw new Error(result?.message || 'Unable to load properties.');
      $('#location-properties').innerHTML = result.data.length ? result.data.map(card).join('') : '<div class="empty">No published listings are currently assigned to this market. Request a current shortlist.</div>';
    } catch (error) { $('#location-properties').innerHTML = `<div class="empty">${esc(error.message)}</div>`; }
  });
})();
